---
deployment:
  tasks:
    - export DEPLOYPATH=/home/cdv/public_html/2026.coldelvalle.edu.mx
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R _app $DEPLOYPATH
    - /bin/cp -R _assets $DEPLOYPATH
    - /bin/cp -R _imgs $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
